add sql for geography
CodeforNepal/nepalmap_federal pull request #12
Opened 2018-07-21 15:47 UTC by crackjack

2018-07-21 22:30 UTC, cliftonmcintosh approved these changes

2018-07-21 22:30 UTC, cliftonmcintosh commented on sql/geography.sql
> +Taplejung,1658,2016,province,Taplejung,district,1
1658 is a duplicate key here. There is a uniqueness constraint on `geo_code` and `geo_level`. I am not sure if there are other duplicates. When I tried to populate the table with this file, it errored here.

I used `cat geography.sql | psql -U wazimap_np -W wazimap_np` to try to populate the table using this file.

2018-07-21 22:30 UTC, cliftonmcintosh requested changes
records must conform to uniqueness constraint.

2018-07-21 22:31 UTC, cliftonmcintosh commented on sql/geography.sql
> +Taplejung,1658,2016,province,Taplejung,district,1
(Accidentally hit "approve")

2018-07-22 03:35 UTC, crackjack commented
The source oknp data has a lot of duplicates
`➜  nepalmap cut -d, -f2 geography_data.csv | sort | uniq -dc`


      2 1
      2 100
      2 1658
      2 190
      3 2
      2 244
      2 268
      2 3
      2 319
      2 4
      2 496
      2 5
      2 507
      2 51
      2 528
      2 545
      2 550
      2 6
      2 614
      3 630
      2 650
      3 671
      2 672
      2 676
      3 678
      2 679
      2 680
      2 7
      2 81

2018-07-22 03:38 UTC, crackjack commented
I'm sure the reason is because each data begins with 1, for province, district and local, and if it increases sequentially then it is certain that they clash in those levels

I'll look into this tomorrow, may be come up with something.

2018-07-29 17:27 UTC, openrijal commented
avoiding duplicates for integers has proved to be difficult than I expected

I see that geocode can be varchar(10), which means something like `pro1`, `dis6736` or `loc44352` should be fine

do you think we can use such codes? it would definitely avoid duplicates and get the work done.

cc: @cliftonmcintosh

2018-07-29 17:30 UTC, cliftonmcintosh commented
@crackjack

I think that should be fine. I don't know of anything in the Wazimap framework that requires the geocode to be an integer.

2018-07-29 18:13 UTC, crackjack commented
updated PR

2018-07-29 18:59 UTC, crackjack commented
new PR with geojson and topojson files matching geoids as in the csv for database entry

2018-07-29 21:31 UTC, cliftonmcintosh commented
Some of the district rows are missing their parent ids:

```
wazimap_np=> select * from wazimap_geography where geo_level = 'district' and parent_code not like 'pro%';;
 id | geo_level | geo_code |      name      | year | square_kms | parent_level | parent_code |   long_name    
----+-----------+----------+----------------+------+------------+--------------+-------------+----------------
 18 | district  | 1475     | Terathum       | 2016 |            | province     |             | Terathum
 25 | district  | 190      | Kavrepalanchok | 2016 |            | province     |             | Kavrepalanchok
 48 | district  | 2807     | Rukum          | 2016 |            | province     |             | Rukum
 58 | district  | 3212     | Manag          | 2016 |            | province     |             | Manag
 60 | district  | 3324     | Tanahun        | 2016 |            | province     |             | Tanahun
 63 | district  | 3487     | Kapilbastu     | 2016 |            | province     |             | Kapilbastu
 64 | district  | 3579     | Nawalparasi    | 2016 |            | province     |             | Nawalparasi
 65 | district  | 3585     | Nawalparasi    | 2016 |            | province     |             | Nawalparasi
 83 | district  | 81       | Sindhupalchowk | 2016 |            | province     |             | Sindhupalchowk
(9 rows)
```

Is there something that is common about this that would explain how it happened?

2018-07-30 23:56 UTC, crackjack commented
The districts are duplicate in the geojson files as well, its from the source that we use, will it be a problem if you keep the duplicates in the geojson but remove them from the CSV? @cliftonmcintosh

2018-07-31 00:02 UTC, cliftonmcintosh commented
I am not sure what happens if there are duplicates in the geojson. It probably depends on how the map responds to a click.

2018-07-31 00:45 UTC, crackjack commented
lets check that out, because I find it difficult to edit the geojson file and remove the duplicates, and without knowing which boundary is actual one

if we just pull the data from csv, that will only give us 1 item for Nawalparasi, that way we might be safe.

updated the PR just now, the main problem is that we don't have source of truth and gathering data from multiple source has caused all this problem

cc: @cliftonmcintosh

2018-07-31 01:31 UTC, cliftonmcintosh commented
Right. We shouldn't have to edit the geojson files. They are too complex for that.

2018-08-05 15:26 UTC, crackjack commented
I have created these new sql files from latest geojsons from Nikesh.

I still had to do a lot of manual work in the district geojson file, but I hope it is worth it.

There is also new geojson files, that might be needed to be replaced, I'll point you the source @cliftonmcintosh

2018-08-05 15:38 UTC, crackjack commented
updated the geojson and topojson files in this PR

2018-08-06 01:59 UTC, cliftonmcintosh approved these changes
Thank you for all of your hard work getting these data imported.

2018-08-06 01:59 UTC, merged